# This file was generated by GoReleaser. DO NOT EDIT.
cask "worktree-switcher" do
  version "0.0.0"

  on_macos do
    on_intel do
      url "https://github.com/TrystanKaes/worktree-switcher/releases/download/v#{version}/worktree-switcher_#{version}_darwin_amd64.tar.gz"
      sha256 "886044ef8a525f67d7b922abd370a49c0c42f09885cf99e379cf7816956e3a5a"
    end
    on_arm do
      url "https://github.com/TrystanKaes/worktree-switcher/releases/download/v#{version}/worktree-switcher_#{version}_darwin_arm64.tar.gz"
      sha256 "29b0b4a230fd990f51f23ff2d8706f68dee042abaa3ff6ae9cefdd8b95738843"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/TrystanKaes/worktree-switcher/releases/download/v#{version}/worktree-switcher_#{version}_linux_amd64.tar.gz"
      sha256 "0fa975b89995731f204a4b39df401052a7e8cb9681c82a77f402c61fbf923b63"
    end
  end

  name "worktree-switcher"
  desc "Interactive TUI for managing and switching between git worktrees"
  homepage "https://github.com/TrystanKaes/worktree-switcher"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "worktree-switcher"

  # No zap stanza required

  caveats <<~EOS
    To finish install add the following to your shell config
    (~/.zshrc, ~/.bashrc, or ~/.bash_profile):

      eval "$(worktree-switcher init)"

    Then restart your shell or run: source ~/.zshrc (or your shell config file).

    FWIW This is needed because shell's can't inherit directory changes from child processes.
    When you use worktree-switcher it runs as a subprocess and some of it's most critical functions (i.e. 'cd'ing into directories) die with it.
    Don't worry, this is the same pattern used by rbenv, nvm, Zoxide, and many other popular tools.
  EOS
end
