# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WorktreeSwitcher < Formula
  desc "Interactive TUI for managing and switching between git worktrees"
  homepage "https://github.com/TrystanKaes/worktree-switcher"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TrystanKaes/worktree-switcher/releases/download/v0.1.0/worktree-switcher_0.1.0_darwin_amd64.tar.gz"
      sha256 "51835ffc847d8050a58e18867c6a2251df847a9eb0595c5ab1a6954a8a1eac45"

      define_method(:install) do
        bin.install "worktree-switcher"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TrystanKaes/worktree-switcher/releases/download/v0.1.0/worktree-switcher_0.1.0_darwin_arm64.tar.gz"
      sha256 "109f6ca8e86958edfde17c50989df61f368b47099cf7528e5e29be87b334f1d0"

      define_method(:install) do
        bin.install "worktree-switcher"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TrystanKaes/worktree-switcher/releases/download/v0.1.0/worktree-switcher_0.1.0_linux_amd64.tar.gz"
      sha256 "0db989e96d2264fde65895d717f319382d04fbb122afc6f0c38d8ede48301379"
      define_method(:install) do
        bin.install "worktree-switcher"
      end
    end
  end

  def caveats
    <<~EOS
      .
      .
      .
      To finish install add the following to your shell config
      (~/.zshrc, ~/.bashrc, or ~/.bash_profile):

        eval "$(worktree-switcher init)"

      Then restart your shell or run: source ~/.zshrc (or your shell config file).

      This is needed because shells can't inherit directory changes from child processes.
      When you use worktree-switcher it runs as a subprocess and some of its most critical
      functions (i.e. cd'ing into directories) die with it. This is the same pattern used
      by rbenv, nvm, Zoxide, and many other popular tools.
      .
      .
      .
    EOS
  end
end
