# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WorktreeSwitcher < Formula
  desc "Interactive TUI for managing and switching between git worktrees"
  homepage "https://github.com/TrystanKaes/worktree-switcher"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TrystanKaes/worktree-switcher/releases/download/v0.0.3/worktree-switcher_0.0.3_darwin_amd64.tar.gz"
      sha256 "6285ab3b4516bee3aa07b62a238f1b2cbbdeab69b83366eb2cbaa8dd75fa9970"

      define_method(:install) do
        bin.install "worktree-switcher"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TrystanKaes/worktree-switcher/releases/download/v0.0.3/worktree-switcher_0.0.3_darwin_arm64.tar.gz"
      sha256 "26ccca37ef85480965568872cf699d2e322a020bc9076c0df4ec0cae152edc51"

      define_method(:install) do
        bin.install "worktree-switcher"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TrystanKaes/worktree-switcher/releases/download/v0.0.3/worktree-switcher_0.0.3_linux_amd64.tar.gz"
      sha256 "ac68087c8189875e816db88abb623bca7df940741856607ed8d2b0ffce0a3116"
      define_method(:install) do
        bin.install "worktree-switcher"
      end
    end
  end

  def caveats
    <<~EOS
      .
      .
      .
      To finish install add the following to your shell config
      (~/.zshrc, ~/.bashrc, or ~/.bash_profile):

        eval "$(worktree-switcher init)"

      Then restart your shell or run: source ~/.zshrc (or your shell config file).

      This is needed because shells can't inherit directory changes from child processes.
      When you use worktree-switcher it runs as a subprocess and some of its most critical
      functions (i.e. cd'ing into directories) die with it. This is the same pattern used
      by rbenv, nvm, Zoxide, and many other popular tools.
      .
      .
      .
    EOS
  end
end
